/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CircularProgressBarImport } from './routes/circular-progress-bar'
import { Route as AnimatedGradientTextImport } from './routes/animated-gradient-text'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const CircularProgressBarRoute = CircularProgressBarImport.update({
  id: '/circular-progress-bar',
  path: '/circular-progress-bar',
  getParentRoute: () => rootRoute,
} as any)

const AnimatedGradientTextRoute = AnimatedGradientTextImport.update({
  id: '/animated-gradient-text',
  path: '/animated-gradient-text',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/animated-gradient-text': {
      id: '/animated-gradient-text'
      path: '/animated-gradient-text'
      fullPath: '/animated-gradient-text'
      preLoaderRoute: typeof AnimatedGradientTextImport
      parentRoute: typeof rootRoute
    }
    '/circular-progress-bar': {
      id: '/circular-progress-bar'
      path: '/circular-progress-bar'
      fullPath: '/circular-progress-bar'
      preLoaderRoute: typeof CircularProgressBarImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/animated-gradient-text': typeof AnimatedGradientTextRoute
  '/circular-progress-bar': typeof CircularProgressBarRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/animated-gradient-text': typeof AnimatedGradientTextRoute
  '/circular-progress-bar': typeof CircularProgressBarRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/animated-gradient-text': typeof AnimatedGradientTextRoute
  '/circular-progress-bar': typeof CircularProgressBarRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/animated-gradient-text' | '/circular-progress-bar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/animated-gradient-text' | '/circular-progress-bar'
  id: '__root__' | '/' | '/animated-gradient-text' | '/circular-progress-bar'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AnimatedGradientTextRoute: typeof AnimatedGradientTextRoute
  CircularProgressBarRoute: typeof CircularProgressBarRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AnimatedGradientTextRoute: AnimatedGradientTextRoute,
  CircularProgressBarRoute: CircularProgressBarRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/animated-gradient-text",
        "/circular-progress-bar"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/animated-gradient-text": {
      "filePath": "animated-gradient-text.tsx"
    },
    "/circular-progress-bar": {
      "filePath": "circular-progress-bar.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
